NAME: TD3
CHECKPOINT_INTERVAL: 50
MAX_NO_IMPROVEMENT_EVALS: 3
EPISODES: 2500

agent_params:
  action_noise: null
  activation_fn: tanh
  batch_size: 200
  gamma: 0.9766519262714228
  gradient_steps: 8
  learning_rate: 8.86666407593999e-05
  learning_starts: 600
  lr_schedule: linear_decrease
  n_nodes_layer: 1024
  n_not_shared_layers: 8
  policy_delay: 10
  target_noise_clip: 0.42580299347844197
  target_policy_noise: 0.09564547952520154
  tau: 0.0028384818651399457