NAME: TD3
CHECKPOINT_INTERVAL: 50
MAX_NO_IMPROVEMENT_EVALS: 3
EPISODES: 2500

agent_params:
  action_noise: null
  activation_fn: tanh
  batch_size: 200
  gamma: 0.9544954093870411
  gradient_steps: 9
  learning_rate: 0.0001237532031611073
  learning_starts: 650
  lr_schedule: constant
  n_nodes_layer: 1024
  n_not_shared_layers: 8
  policy_delay: 10
  target_noise_clip: 0.3366521713543903
  target_policy_noise: 0.1582825554974576
  tau: 0.0023172611626971077
