# to update versions run: pre-commit autoupdate
# to install pre-commit hooks run: pre-commit install

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    # list of supported hooks: https://pre-commit.com/hooks.html
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: debug-statements
    - id: detect-private-key
    - id: check-toml
    - id: requirements-txt-fixer
    # - id: name-tests-test

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.4.8"
    hooks:
        # run the linter
        - id: ruff
          args: ["--line-length", "88"]
        # run the formatter - basically the same as running black: https://docs.astral.sh/ruff/formatter/
        - id: ruff-format
          args: ["--line-length", "88"]

# sorting your imports
-   repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: [--profile, black]
