repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      # - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
      - id: check-toml

  # python code formatting
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        additional_dependencies: ["click==8.0.4"]
        entry: poetry run black
        language_version: python3.10

  # python code analysis. Note: use a linter while coding as well
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        entry: poetry run flake8
        language: system
        types: [python]

  # sorting your imports
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  # # checking your type annotations
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v0.971" # Use the sha / tag you want to point at
  #   hooks:
  #     - id: mypy
  #   args: [--no-strict-optional, --ignore-missing-imports]

  # clearing notebook output cell
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout

  # # python docstring formatting
  # -   repo: https://github.com/myint/docformatter
  #     rev: v1.4
  #     hooks:
  #     - id: docformatter
  #     args: [--in-place, --wrap-summaries, "99", --wrap-descriptions, "92"]

  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
        types: [yaml]

  # update python syntax to newer versions of python
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
# to update versions run: pre-commit autoupdate
