repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          # list of supported hooks: https://pre-commit.com/hooks.html
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
            args: ["--maxkb=1000"]
          - id: debug-statements
          - id: detect-private-key
          - id: check-toml

    # run ruff autofix before black and isort
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: "v0.0.274"
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]

    - repo: https://github.com/ambv/black
      rev: 23.3.0
      hooks:
          - id: black
            additional_dependencies: ["click==8.0.4"]
            entry: poetry run black
            language_version: python3.11

    - repo: https://github.com/timothycrosley/isort
      rev: 5.12.0
      hooks:
          - id: isort

    # # checking your type annotations
    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: "v1.2.0" # Use the sha / tag you want to point at
    #   hooks:
    #   - id: mypy
    #     args: [--ignore-missing-imports]

    # clearing notebook output cell, to avoid checking and reduce size
    - repo: https://github.com/kynan/nbstripout
      rev: 0.6.1
      hooks:
          - id: nbstripout

    # # python docstring formatting
    # -   repo: https://github.com/myint/docformatter
    #     rev: v1.4
    #     hooks:
    #     - id: docformatter
    #     args: [--in-place, --wrap-summaries, "99", --wrap-descriptions, "92"]


# to update versions run: pre-commit autoupdate
