name: rl_cutter
channels:
- conda-forge
- defaults
dependencies:
- python=3.9.7
- joblib=1.1.0
- matplotlib=3.5.1
- numpy
- pandas
- pip
- spyder-kernels=2.1
- pip:
  - optuna==2.10.0
  - stable-baselines3==1.5